### ISSUE TITLE
[Bug] ParseLatinFont function returns minor font

### ISSUE THREAD

**Issue by rahul-dutt-sharma** [ShapeCrawler/ShapeCrawler#111]
The ParseLatinFont function returns minor font. Its possible that the font on the shape is a major font

**Comment by rahul-dutt-sharma** [comment]
From what I could gather, the development can be done by using PlaceHolder Class
https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.presentation.placeholdershape?view=openxml-2.8.1 

By inspecting the XML of the document, I think that the shape class in this project can keep a mapping of the placeholder values which can then map to the applied Layout xml and pick the major or minor value by reading ListStyle and using the appropriate level Level**X**ParagraphProperties
https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.drawing.liststyle?view=openxml-2.8.1

**Comment by adamshakhabov** [comment]
Yep, I think you are right. Honestly, I am not happy about the current placeholders parsing. BTW, I have not good investigated `PlaceholderShape` class, but it seems, does not have direct access to the corresponding shape on Slide Layout. Manual searching by `PlaceholderShape.Index` should be done to get placeholder content from the Slide Layout.

In addition to `ListStyle`, there is a case when `DefaultTextStyle` from the presentation level should be [parsed to get font data](https://github.com/ShapeCrawler/ShapeCrawler/blob/master/ShapeCrawler/Settings/PresentationData.cs#L35).

_Working on the fix..._

**Comment by rahul-dutt-sharma** [comment]
Yes, the manual searching is the part where I am stuck, thinking about it.

**Comment by adamshakhabov** [comment]
Closed via [**0.16.1**](https://github.com/ShapeCrawler/ShapeCrawler/releases/tag/v0.16.1) release.

Feel free to re-open or create a new one if you find a bug in font data parsing.
