### ISSUE TITLE
Add external slide

### ISSUE THREAD

**Issue by adamshakhabov** [ShapeCrawler/ShapeCrawler#12]
Add `ISlideCollection.AddExternal(ISlide externalSlide)`

#### Usefull links

- https://stackoverflow.com/questions/49453527/copying-a-slide-from-one-presentation-to-another-using-open-xml-sdk
- https://social.msdn.microsoft.com/Forums/Lync/en-US/2ceb0ac3-f5b4-4345-b1e9-5a5a4319c539/how-i-can-clone-one-slide-to-new-presentation-?forum=oxmlsdk

**Comment by Offbeatmammal** [comment]
to add an external slide, could that be achieved by opening up the ability to insert a slide into a presentation (at a specific point) then using an existing slide object as the source/template?

eg something like:
    using IPresentation p1 = SCPresentation.Open("s1.pptx", isEditable: false);
    using IPresentation p2 = SCPresentation.Open("s2.pptx", isEditable: true);

    var sl = p1.Slides(5);
    p2.Slides(6).insertAfter(sl);

similar logic could also apply to removing slides
    `p2.Slides(6).remove;`

or moving slides
    `p2.Slides(5).moveBefore(1);`

(having looked at the internal structure of pptx files, I appreciate that waving round pseudocode for what I want might not be helpful or practical!)

**Comment by adamshakhabov** [comment]
There is an idea to add one more method `ISlideCollection.Insert(ISlide slide, int slideNumber)`. Its behaviour will similar suggested `ISlide.InsertedAfter(ISlide slide)`.

Agree regard `ISlide.MoveBefore(int slideNumber)` — we need something like that. #140 issue has been created for this.

Sounds good?

**Comment by adamshakhabov** [comment]
Added to [**v0.21.0**](https://github.com/ShapeCrawler/ShapeCrawler/releases/tag/v0.21.0) release.
