### ISSUE TITLE
Add support for NetStandard 2.0

### ISSUE THREAD

**Issue by PrzemyslawKlys** [ShapeCrawler/ShapeCrawler#127]
Would it be possible to add NetStandard 2.0 as a target? I know there is 2.1, but with 2.0 it also would work on Net 4.6.1 which is the most commonly available. 

![image](https://user-images.githubusercontent.com/15063294/114362469-a9603480-9b77-11eb-8014-9de38bc8661a.png)

**Comment by adamshakhabov** [comment]
It should work since it has v4.6.1 target. Could you double-check.

![image](https://user-images.githubusercontent.com/5969304/114367928-9bb1ab80-9b85-11eb-9657-ee9c6715e383.png)

**Let me know if it is not true.**

**Comment by PrzemyslawKlys** [comment]
It targets 4.6.1 explicitly but I want to use a single DLL (net standard 2.0) that will target both ends.

**Comment by adamshakhabov** [comment]
Got it. Yes, we can add .NET Standard 2.0 target in the next v0.19.0 version. However, I think it should be removed in the first 1.0.0 stable version since .NET Standard 2.0 is **out of support**.

**Comment by PrzemyslawKlys** [comment]
Thank you. Not sure about out of support but Net Standard 2.0 is the only one that supports code sharing between net framework and all other implementations of .NET according to https://docs.microsoft.com/en-us/dotnet/standard/net-standard

> .NET Standard not deprecated
> .NET Standard is still needed for libraries that can be used by multiple .NET implementations. We recommend you target .NET Standard in the following scenarios:
> 
> Use netstandard2.0 to share code between .NET Framework and all other implementations of . NET.
> Use netstandard2.1 to share code between Mono, Xamarin, and .NET Core 3.x.
>

**Comment by adamshakhabov** [comment]
Closed by adding .NET Standard 2.0 target in the [**v0.19.0**](https://github.com/ShapeCrawler/ShapeCrawler/releases/tag/v0.19.0) release.
