### ISSUE TITLE
How to add pictures to presentation (instead of replace)?

### ISSUE THREAD

**Issue by sep2** [ShapeCrawler/ShapeCrawler#135]
Hi, Thanks for the greak library!

I'm looking for a way to add images to the Presentation and replace some pictures in the slides.

I found [this test](https://github.com/ShapeCrawler/ShapeCrawler/blob/f73d688fab28d353630bb327a31dedaf8acf0dd8/ShapeCrawler.Tests.Unit/PictureTests.cs#L40) does similar, but It will replace the old picture in all referenced slides. 

I only want to replace specific slide's picture, and keep other slides untouch. Can you point me any resouce that can help?

**Comment by adamshakhabov** [comment]
Hello! Thank you for your feedback :)

Yep, the current version has such issue :( I think I can fix it faster (next 2-3 days) since I've already investigated it.

By the way, the idea is just to create a new `ImagePart` instead of changing a property of the existing one.

**Comment by adamshakhabov** [comment]
Closed by [**v0.20.1**](https://github.com/ShapeCrawler/ShapeCrawler/releases/tag/v0.20.1) release.

Please feel free to re-open or create a new one if it still does not work correctly.
