### ISSUE TITLE
Add setter for Font.ColorFormat.Color

### ISSUE THREAD

**Issue by Offbeatmammal** [ShapeCrawler/ShapeCrawler#138]
Currently we have a getter for `Font.ColorFormat.Color` so we can see what the existing color of text is, but unlike (eg) `isBold` we can't set color to (eg) rgb(128,128,128)

Would also be good to be able to set the background (highlight) color (is this related to #25?)

**Comment by adamshakhabov** [comment]
Agree, we need to add the **setter** to be able to **change font colour**.
_________
No, it is not related to #25. The #25 issue idea is adding some anonymize method to `ISlide` interface allowing delete/change sensitive text content from the slide. 
_________
Regard 

> Would also be good to be able to set the background (highlight) color

do you mean set **slide's** background with solid color?

**Comment by adamshakhabov** [comment]
Got it. #139 has been created for this.
