### ISSUE TITLE
Create new slide

### ISSUE THREAD

**Issue by adamshakhabov** [ShapeCrawler/ShapeCrawler#141]
Add API to be able to add a new slide, e.g. `ISlide ISlideCollection.AddNewSlide()`.

Useful links:

- https://docs.microsoft.com/en-us/office/open-xml/how-to-insert-a-new-slide-into-a-presentation

**Comment by YaseenYo** [comment]
Hello @adamshakhabov, can I contribute to this project?

**Comment by adamshakhabov** [comment]
Hello @YaseenYo. Yes, of cause! Do you wanna check this issue?

**Comment by YaseenYo** [comment]
Please help me get started with this...

**Comment by YaseenYo** [comment]
@adamshakhabov Can I set up this project using VsCode?

**Comment by adamshakhabov** [comment]
Yes, you should. The library doesn't have some specific settings or dependencies for non-Visual Studio IDE or non-Windows OS.

Check this general tutorial [Debug a .NET console application using Visual Studio Code](https://docs.microsoft.com/en-us/dotnet/core/tutorials/debugging-with-visual-studio-code#start-debugging)

**Comment by YaseenYo** [comment]
I have completed setting up my environment. @adamshakhabov it would be really helpful if you could elaborate on this issue.

**Comment by YaseenYo** [comment]
@adamshakhabov I have to write the functionality for the `AddNewSlide()` function to create a new slide... am I guessing it write?

**Comment by adamshakhabov** [comment]
Right.

**Comment by adamshakhabov** [comment]
@YaseenYo, I started adding [CONTRIBUTING.MD](https://github.com/ShapeCrawler/ShapeCrawler/blob/master/CONTRIBUTING.md). Please take a look at this document. It can help you make starting.

**Comment by adamshakhabov** [comment]
@YaseenYo, I think there is no progress?🙂

**Comment by YaseenYo** [comment]
hello @adamshakhabov , Its been long time I visited this project

**Comment by YaseenYo** [comment]
I see Insert and Add methods have been implemented already

**Comment by adamshakhabov** [comment]
Correct. But these methods manipulate _existing_ slide. They do not construct slide from _scratch_.

**Comment by adamshakhabov** [comment]
The new `ISlideCollection.AddEmptySlide()` method has been added. It will be available in the next 0.40.0 version.
