### ISSUE TITLE
Add video content on slide

### ISSUE THREAD

**Issue by adamshakhabov** [ShapeCrawler/ShapeCrawler#169]
- https://stackoverflow.com/questions/44074387/how-to-insert-video-in-pptx-using-open-xml-sdk

**Comment by wbalbo** [comment]
Hi, I want to help, I will try to solve this issue.

**Comment by adamshakhabov** [comment]
Hello. Would be great! Will wait for Pull Request :)

**Comment by wbalbo** [comment]
Hey, how did you debug this project? Do you attach to a console app that uses ShapeCrawler?

**Comment by adamshakhabov** [comment]
- **TDD**: I develop via TDD, thus most of the time debugging occurred inside unit-test.
- **OOXML Viewer**: pptx-file's XML structure is investigated in Visual Studio Code with [OOXML Viewer](https://marketplace.visualstudio.com/items?itemName=yuenm18.ooxml-viewer) extension. One of the good features of this extension is track changes of modified presentation.
- **Open XML SDK 2.5 Productivity Tool**: In your case, using [Open XML SDK 2.5 Productivity Tool](https://github.com/OfficeDev/Open-XML-SDK/releases/tag/v2.5) can be useful. For example, you can create a test presentation with minimum data and video content, then open it with Open XML SDK 2.5 Productivity Tool which can generate you C#-code.

**Comment by wbalbo** [comment]
Thanks for your answer.

I'm using the productivity tool to see the code generated.

I will try to use the test project to understand the life cycle of the code and try to see where is the best location to put this video part.

**Comment by adamshakhabov** [comment]
Thank you for your contribution!

**Comment by wbalbo** [comment]
No problem, I'm just a bit slow because I'm in the middle of technical interviews for some remote companies, but as soon as I can I want to help more in this project.

**Comment by wbalbo** [comment]
Coming back to this!

**Comment by wbalbo** [comment]
Sorry, many days doing technical tests and interviews, trying to come back at least in the weekends.

A bit hard to figure out where I put the code to test this, but after I finish I will ask for more details to you.

Thanks.

**Comment by adamshakhabov** [comment]
I recently added `IShapeCollection.AddNewAudio()` — a new method to add audio shape — this might be useful for your task: https://github.com/ShapeCrawler/ShapeCrawler/blob/master/ShapeCrawler/Collections/ShapeCollection.cs#L209-L313

**Comment by wbalbo** [comment]
Thanks, interesting.

I found this answer that can help a bit with my task, I will see your code too.

https://stackoverflow.com/a/61593910/8545680

**Comment by wbalbo** [comment]
Hey, I think I completed, testes with a mp4 file. Will upload a .avi file to project to test.

I needed to change a bit the PictureHandler.cs class, in the override Create method, will make a PR after test with an avi file.

**Comment by wbalbo** [comment]
142/146 tests passed, 4 skipped, seems good to me haha.
