### ISSUE TITLE
Create presentation?

### ISSUE THREAD

**Issue by PrzemyslawKlys** [ShapeCrawler/ShapeCrawler#170]
In all your examples you're showing how to add something to an existing presentation. Is there a way one could do a presentation from scratch? Could you show me how?

**Comment by adamshakhabov** [comment]
No, creating a presentation from scratch [https://github.com/ShapeCrawler/ShapeCrawler/issues/53](https://github.com/ShapeCrawler/ShapeCrawler/issues/53) is not available yet.

**Comment by PrzemyslawKlys** [comment]
Thank you.
