### ISSUE TITLE
Fix IShape.CustomData

### ISSUE THREAD

**Issue by adamshakhabov** [ShapeCrawler/ShapeCrawler#175]
The property `IShape.CustomData` does not store string.

**Comment by wbalbo** [comment]
Hey, I was testing and seems to me that this property stores string.

Where does this problem happen?

**Comment by adamshakhabov** [comment]
Hmm, that really works :) We have [CustomData_ReturnsCustomDataOfTheShape_WhenShapeWasAssignedSomeCustomData](https://github.com/ShapeCrawler/ShapeCrawler/blob/master/ShapeCrawler.Tests.Unit/ShapeTests.cs#L339-L349) test for this case which is also passed. I am probably confused.

@wbalbo, thank you for your contribution!
