### ISSUE TITLE
Add method to add table on a slide

### ISSUE THREAD

**Issue by adamshakhabov** [ShapeCrawler/ShapeCrawler#198]
### Discussed in https://github.com/ShapeCrawler/ShapeCrawler/discussions/197

<div type='discussions-op-text'>

<sup>Originally posted by **tleclaire** January 14, 2022</sup>
Can I create tables in slides with this?

Best regards
Thomas </div>

**Comment by kongyuanchao** [comment]
How to create a pptx file using ShapeCrawler?

**Comment by adamshakhabov** [comment]
It doesn't have yet such opportunity.

**Comment by adamshakhabov** [comment]
The new `SCPresentation.Create()` method to create a presentation has been added and will be available in the next v0.39.0 version.
