### ISSUE TITLE
Unable to cast object of type 'ShapeCrawler.Drawing.LayoutPicture' to type 'ShapeCrawler.IPicture'

### ISSUE THREAD

**Issue by hhq365** [ShapeCrawler/ShapeCrawler#230]
If the picture is from masterSlide,then the type of shape is ShapeCrawler.Drawing.LayoutPicture. It's internal class,and It have not implement the interface ShapeCrawler.IPicture,Then I can't find a way to get the image,Can you support this?

**Comment by adamshakhabov** [comment]
Hi. Thank you for the issue report. I was able to reproduce the issue. Fixing...

**Comment by hhq365** [comment]
> Hi. Thank you for the issue report. I was able to reproduce the issue. Fixing...

Hi.Thank you for quick reply.I saw you already fix it in #230.
I have another problem now,how can i got the extension of these images?
Can you public the file name,or give an extension-name?
