### ISSUE TITLE
Even though shapes.addnewvideo() adds the video to the specified slide but i think the parameters xPixel and yPixels donot work because the added video remains small size in the ppt even after changing the values of these parameter

### ISSUE THREAD

**Issue by aman-gill22** [ShapeCrawler/ShapeCrawler#254]
![image](https://user-images.githubusercontent.com/80083267/170735836-ca2317a7-f5bd-4c9d-9337-951c478b37ef.png)

![image](https://user-images.githubusercontent.com/80083267/170735704-f699082a-8394-4085-8601-80740236c74a.png)

WHAT I ACTUALLY WANT TO DO IS : add the video in the slide covering the full screen

**Comment by adamshakhabov** [comment]
`xPixel` and `yPixels` parameters of `.AddNewVideo()` method provide shape _location_ on slide. To update width/height _size_ you should update `IShape.Width`/`IShape.Height` property.

**Comment by aman-gill22** [comment]
thanks
