### ISSUE TITLE
Loading data for chart only loads the first element

### ISSUE THREAD

**Issue by sergsuhanov** [ShapeCrawler/ShapeCrawler#259]
Hi, loading data for chart only loads the first element
method: ChartPointCollection.Create
example data:

<?xml version="1.0"?>
<c:numRef xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart">
<c:f>Лист1!$B$2:$L$2</c:f>
<c:numCache>
<c:formatCode>0.0</c:formatCode>
<c:ptCount val="11"/>
<c:pt idx="0"><c:v>183</c:v></c:pt>
<c:pt idx="1"><c:v>13</c:v></c:pt>
<c:pt idx="2"><c:v>105.39999999999998</c:v></c:pt>
<c:pt idx="3"><c:v>183</c:v></c:pt>
<c:pt idx="4"><c:v>169</c:v></c:pt>
<c:pt idx="5"><c:v>214</c:v></c:pt>
<c:pt idx="6"><c:v>235.3</c:v></c:pt>
<c:pt idx="7"><c:v>322.60000000000002</c:v></c:pt>
<c:pt idx="8"><c:v>244.35174910000001</c:v></c:pt>
<c:pt idx="9"><c:v>290.02501100000001</c:v></c:pt>
<c:pt idx="10"><c:v>303.99398339999999</c:v></c:pt>
</c:numCache>
</c:numRef>

if you modify the code, then the data is loaded, but I'm not sure if this is correct

 ```
           // Generate points
            var chartPoints = new List<ChartPoint>(pointAddresses.Count);
            for (int i = 0; i < pointAddresses.Count; i++) {
                var address = pointAddresses[i];
                /*
                NumericValue? cNumericValue = null;
                // Empty cells of range don't have the corresponding C.NumericValue.
                if (i < cNumericValues?.Count)
                {
                    cNumericValue = cNumericValues[i];
                }

                chartPoints.Add(new ChartPoint(chart,  dataSheetName, address, cNumericValue));
                */
                foreach (var cNumericValue in cNumericValues) {
                    chartPoints.Add(new ChartPoint(chart, dataSheetName, address, cNumericValue));
                }
            }
```

**Comment by adamshakhabov** [comment]
Hello @sergsuhanov,

thank you for the issue report.

Yes, it is possible. The library's APIs for Charts manipulating are poor yet. It doesn't cover all Chart types.

Would be happy to review PR🙂
