### ISSUE TITLE
Nested items changing type

### ISSUE THREAD

**Issue by cfelstead** [ShapeCrawler/ShapeCrawler#263]
### Question / Description

Hi,

Love the library, however, I am coming across a problem that probably has a simple solution but it is eluding me so far. I am trying to access controls that are nested. For example, 

`pres.Slides[2].Shapes.GetById<IGroupShape>(12).Shapes.GetByName<IPicture>("TopPerformingFlag")`

However, the types returned from GetById and GetByName do not match the original. `pres.Slides[2].Shapes` returns a IShapeCollection which has the GetById and GetByName methods. `pres.Slides[2].Shapes.GetById<IGroupShape>(12).Shapes` is a IReadOnlyCollection<IShape> and misses these method calls.

Any advice?

### Implementation

- [x] for Slide
- [x] for Slide Layout
- [x] for Slide Master

**Comment by adamshakhabov** [comment]
Hello. Thank you for the feedback :)

Hmm, it is bad. The collection of nested shapes also should be `IShapeCollection`. 

Will fix this in the future version. Also, Pull Request is well come🙂

For now, you can use the following  workaround:

```C#
using var pres = SCPresentation.Open("get-by-name.pptx", false);
var groupShape = pres.Slides[0].Shapes.GetByName<IGroupShape>("Group 1");

// Get child Picture shape by name
var pictureShape = groupShape.Shapes.OfType<IPicture>().First(s => s.Name == "Picture 1");

// Get child AutoShape shape by name
var autoShape = groupShape.Shapes.OfType<IAutoShape>().First(s => s.Name == "AutoShape 1");
```

Let me know if it is not what you are talking about.

**Comment by cfelstead** [comment]
Thank you. That is my current workaround.
