### ISSUE TITLE
Unable to change the color of a shape

### ISSUE THREAD

**Issue by femo1de** [ShapeCrawler/ShapeCrawler#267]
I want to change the color of a shape. I expected to be able to do this by changing the SolidColor Property of the IAutoShape, however this is a readonly property, so this doesnt work:

`((IAutoShape)targetShape).Fill.SolidColor = Color.Green`

## Pull Requests
- https://github.com/ShapeCrawler/ShapeCrawler/pull/269

**Comment by adamshakhabov** [comment]
The new `IShapeFill.SetHexSolidColor(string hex)` method has been implemented to set a solid color as the shape fill. The feature will be accessed in the next _0.36.0_ version.
