### ISSUE TITLE
SaveAs() corrupts internal structure naming

### ISSUE THREAD

**Issue by adamshakhabov** [ShapeCrawler/ShapeCrawler#271]
### Discussed in https://github.com/ShapeCrawler/ShapeCrawler/discussions/266

<div type='discussions-op-text'>

<sup>Originally posted by **shanaki** August 25, 2022</sup>
When open presentation slide by IPresentation.Open() and then just save it by IPresentation.SaveAs().
Rename suffix of the saved file to *.zip, then unzip and see ppt/slides folder.
slide*.xml filename are changed like slide25555.xml, slide67777.xml. Origin ppt contains slide1.xml, slide2.xml and so on.
Why slide xml filename are changed by Save()? Is this intentional behavior? Or, any way to prevent it?
![sc](https://user-images.githubusercontent.com/30141376/186626604-5b8b6eb7-4c65-44e8-bf8e-f8b33390f3fb.png)

</div>

**Comment by adamshakhabov** [comment]
It looks like it is an issue in the underlying Open XML SDK. I've reported issue: https://github.com/OfficeDev/Open-XML-SDK/issues/1197

**Comment by shanaki** [comment]
It looks like https://github.com/dotnet/Open-XML-SDK/issues/1197 already fixed and closed in the latest version. When will it be merged into ShapeCrawler?

**Comment by adamshakhabov** [comment]
@shanaki, thank you for reminder. The issue should have been closed a long time ago since it has already been merged and works correctly, for example in the last version (0.41.4).
