### ISSUE TITLE
Could not load type \u0027ShapeCrawler.AutoShapes.ITextBox

### ISSUE THREAD

**Issue by sergsuhanov** [ShapeCrawler/ShapeCrawler#323]
hi,
new functionality in method SetText (this.AutoFitType == SCAutoFitType.Shrink) is not supported in linux

**Comment by adamshakhabov** [comment]
Hello.

Yep, it is possible😥 since recently I made a migration from `System.Drawing` to `SkiaSharp`. 

Does it happen in the `master` branch or in v0.33.0? Could you please share more exception details?

**Comment by sergsuhanov** [comment]
hi,
in the master branch it's ok
the problem is only in version .33

**Comment by adamshakhabov** [comment]
@sergsuhanov, when you have time, please check whether it is ok in this build [**v0.33.1-beta.1.zip**](https://github.com/ShapeCrawler/ShapeCrawler/files/9666341/ShapeCrawler.0.33.1-beta.1.zip).

**Comment by adamshakhabov** [comment]
The issue will be closed. Feel free to re-open this if the bug is still present.

**Comment by sergsuhanov** [comment]
thanks
