### ISSUE TITLE
Add ITable.AppendRow()

### ISSUE THREAD

**Issue by adamshakhabov** [ShapeCrawler/ShapeCrawler#326]
### Testing

- [x] SCTableRow.CloneRow()✅
- [x] ITable.RemoveRowAt()✅
- [x] ITable.AppendRow() 🟨

### Context
PR: https://github.com/ShapeCrawler/ShapeCrawler/pull/324

**Comment by adamshakhabov** [comment]
@femo1de, thank you for contributing APIs to operate tables!

While testing [**ITable.AppendRow()**](https://github.com/ShapeCrawler/ShapeCrawler/blob/c831048278591ed3f2069d0ba2c55a707bca44d3/ShapeCrawler/Tables/ITable.cs#L47) (the code was refactored) I found it a little bit strange. It gets `DocumentFormat.OpenXml.Drawing.TableRow` object as a parameter. Do we really want to make it **public** that operates directly Open XML SDK (DocumentFormat.OpenXml) instance?

If yes, could you please add a unit test for `ITable.AppendRow()` to see its real use cases?

**Comment by femo1de** [comment]
Hi, I implemented it via SCRow first, however that object would require a fixed .Index property that you can not overwrite. From a users perspective, I would have found it confusing having to provide an index if I just want to append a row to the bottom of a table.
But you are right, this should probably be internal!
________________________________
