### ISSUE TITLE
Support for Find and Replace text in entire slide.

### ISSUE THREAD

**Issue by bannarisoftwares** [ShapeCrawler/ShapeCrawler#358]
How to find and replace the text in entire slide.

**Comment by adamshakhabov** [comment]
Here is an example of how to replace text on a first slide:

```c#
using var pres = SCPresentation.Open("some.pptx");
var textFrames = pres.Slides[0].GetAllTextFrames();

foreach (var textFrame in textFrames)
{
    textFrame.Text = "some text";
}

pres.Save();
```

**Comment by bannarisoftwares** [comment]
Ok... Great!!! Will check that... Thanks @adamshakhabov for reply :)

**Comment by bannarisoftwares** [comment]
Hi @adamshakhabov , How to Find , then replace the given text with finded one?

**Comment by adamshakhabov** [comment]
Hello @bannarisoftwares!

Aah... you mean, for example, there is slide with two shapes:

```
shape1.Text = "Some awesome text"
shape2.Text = "Maybe it is also awesome text"
```

and you can Find: "awesome", Replace: "awesome2" to get output:

```
shape1.Text = "Some awesome2 text"
shape2.Text = "Maybe it is also awesome2 text"
```
right?

**Comment by bannarisoftwares** [comment]
Excatly @adamshakhabov correct !!! Is it possible @adamshakhabov ?

**Comment by bannarisoftwares** [comment]
Any updates @adamshakhabov ? :)

**Comment by adamshakhabov** [comment]
Try the following custom `ReplaceText()` method:

```c#
void ReplaceText(ISlide slideParam, string oldValue, string newValue)
{
    var allParagraphs = slideParam.GetAllTextFrames().SelectMany(tf => tf.Paragraphs);
    var allPortions = allParagraphs.SelectMany(p => p.Portions);
    
    foreach (var portion in allPortions)
    {
        portion.Text = portion.Text.Replace(oldValue, newValue);
    }
}

using var pres = SCPresentation.Open("some.pptx");
var slide = pres.Slides[0];

ReplaceText(slide, "awesome", "awesome2");

pres.Save(); 
```

It is a workaround and this will not work for all cases, for example, when found `oldValue` is consist of different formats.

We should implement some new `IParagraph.ReplaceText(string oldValue, newValue)`.

**Comment by adamshakhabov** [comment]
The new `IParagraph.ReplaceText(string oldValue, string newValue)` method has been added. 

It will be accessed in the next 0.37.0 version. You can use it in the following way:

```C#
using var pres = SCPresentation.Open("some.pptx");
var slideParagraphs = pres.Slides[0].GetAllTextFrames().SelectMany(tf => tf.Paragraphs);

foreach (var paragraph in slideParagraphs)
{
    paragraph.ReplaceText("awesome", "awesome2");
}

pres.Save();
```

**Comment by bannarisoftwares** [comment]
Thanks @adamshakhabov ... Will check.

**Comment by bannarisoftwares** [comment]
When version 0.37.0 will be released? I am waiting for IParagraph.ReplaceText :)

**Comment by adamshakhabov** [comment]
Use [**0.37.0-beta.1**](https://github.com/ShapeCrawler/ShapeCrawler/files/9936509/ShapeCrawler.0.37.0-beta.1.zip) for a while.

The stable 0.37.0 version is planned by 14.11.2022
