### ISSUE TITLE
Update Theme

### ISSUE THREAD

**Issue by adamshakhabov** [ShapeCrawler/ShapeCrawler#369]
- [x] update theme color
- [x] update theme font

**Comment by Wenfengcheng** [comment]
@adamshakhabov change theme font is also an important function.

**Comment by Wenfengcheng** [comment]
@adamshakhabov ThemeFont contains **EastAsianFont** and **LatinFont**, maybe two properties need to be exposed.
And the font of textFrame also should have this two properties.

**Comment by adamshakhabov** [comment]
@Wenfengcheng, thank you for this report.

I'm not very family with this. We will do it in the separate https://github.com/ShapeCrawler/ShapeCrawler/issues/419 issue

**Comment by adamshakhabov** [comment]
The new `ISlideMaster.ITheme` property has been added. It contains properties that allow read/update fonts and colors of theme scheme.

The feature will be available in the next v0.40.0 version.
