### ISSUE TITLE
Getting an error while trying to update AutoShape Text that is inside IGroupShape

### ISSUE THREAD

**Issue by Rahul00900800** [ShapeCrawler/ShapeCrawler#452]
var autoShapes_scores = ((IGroupShape)slide.Shapes[6]).Shapes.Where(sp => sp is IAutoShape).ToList();
((IAutoShape)autoShapes_scores[0]).TextFrame.Text="xyz"

Exception - Height coordinate of grouped shape cannot be changed.

**Comment by adamshakhabov** [comment]
Thank you for the bug report. I was able to reproduce it, and we will fix it.

**Comment by hedayatkamalian** [comment]
i still have same problem with latest version 0.43.0

**Comment by adamshakhabov** [comment]
@hedayatkamalian, I wasn't able to reproduce it with 0.43.0. Could you share your presentation?

If you don't want to share it publicly you can send it to the Email theadamo86@gmail.com

**Comment by hedayatkamalian** [comment]
@adamshakhabov 
Hi Adam, thank you for your feedback
here is code :

```
var textFrames = slide.GetAllTextFrames();
foreach (var textFrame in textFrames)
                    {
                        // a textFrame which is grouped and with AutofitType = SCAutofitType.Resize
                        foreach (var paragraph in textFrame.Paragraphs)
                        {
                            if (!string.IsNullOrEmpty(paragraph.Text.Trim()))
                            {
                                var translation = "a text with bigger length than original text "
                                //here throws exception
                                paragraph.ReplaceText(paragraph.Text, translation);
                            }

                        }
                    }
```

**Comment by adamshakhabov** [comment]
Hello Hedayat @hedayatkamalian,

unfortunately, I still can't reproduce it. For example, your code works on the following presentation file:

[**grouped.pptx**](https://github.com/ShapeCrawler/ShapeCrawler/files/11219918/grouped.pptx)

```c#
using var pres = SCPresentation.Open("grouped.pptx");
var slide = pres.Slides[0];

var textFrames = slide.GetAllTextFrames();
foreach (var textFrame in textFrames)
{
    foreach (var paragraph in textFrame.Paragraphs)
    {
        if (!string.IsNullOrEmpty(paragraph.Text.Trim()))
        {
            var translation = "a text with bigger length than original text ";
            paragraph.ReplaceText(paragraph.Text, translation);
        }
    }
}

pres.Save();
```

**Comment by hedayatkamalian** [comment]
@adamshakhabov 
try [this ](http://hedkam.ir/office/smart3.pptx)file

**Comment by adamshakhabov** [comment]
It also works on my side

![image](https://user-images.githubusercontent.com/5969304/231972472-fc3a1767-67ff-4e09-8e94-88ad91d8377a.png)

**Comment by adamshakhabov** [comment]
@hedayatkamalian, isn't it still working?

**Comment by hedayatkamalian** [comment]
@adamshakhabov 
yes, the problem hasn't been solved yet.
it's a weird problem, so I've prepared a test project to help you reproduce the exception.
[ShapeCrawlerTest.zip](https://github.com/ShapeCrawler/ShapeCrawler/files/11332034/ShapeCrawlerTest.zip)

**Comment by adamshakhabov** [comment]
Yes, now I get repro.

Thank you. Will research this.

**Comment by adamshakhabov** [comment]
@hedayatkamalian, check this beta release: [ShapeCrawler.0.45.0-beta.1.zip](https://github.com/ShapeCrawler/ShapeCrawler/files/11347575/ShapeCrawler.0.45.0-beta.1.zip)

**Comment by hedayatkamalian** [comment]
@adamshakhabov 
sorry for late response.
the problem is solved in last version . thank you
