### ISSUE TITLE
How to add a connector shape

### ISSUE THREAD

**Issue by samcov** [ShapeCrawler/ShapeCrawler#465]
I only have rectangles and connectors, so I check to see if it's an autoshape: 

if (shape is IAutoShape){ 
     //then add it to the collection 
     var addedShape = cshapeCollection.**AutoShapes**.AddRectangle(shape.X, shape.Y, shape.Width, shape.Height);
}

How do I do that for a connector type, what is the equivalent of **AutoShapes**?,

**Comment by adamshakhabov** [comment]
If you want to determine whether a shape is a connector, you can use the following code:

```c#
using var pres = SCPresentation.Open("some.pptx");

foreach(var shape in pres.Slides[0].Shapes)
{
    if (shape is IConnectionShape connector)
    {
        Console.WriteLine($"The nane of connector shape: {connector.Name}");
    }
}
```

But the subject asks "How to add a connector shape?": this functionality is not currently available.

**Comment by samcov** [comment]
Thanks, I do that in an else, but my question is **how to add the connector to the shapes collection to write it out**, and it appears that's not been implemented yet.

However, until then, would it be possible for you to have an "**InsertXMLInSlide**" function, that would allow us to add arbitrary XML to the slide, because the connector, at least Elbow types XML appears to be relatively straight forward.

You specify the start and end autoshapes(by id), then the starting rectangle & the width/height cx/cy to get the bounding rectangle as minimal parameters(see below). Of course, I don't believe you use the <p:cxnSp> starting tag.
         <p:cxnSp>
            <p:nvCxnSpPr>
               <p:cNvPr id="12" name="Elbow Connector 11" />
               <p:cNvCxnSpPr>
                  <a:stCxn id="5" idx="3" />
                  <a:endCxn id="6" idx="1" />
               </p:cNvCxnSpPr>
               <p:nvPr />
            </p:nvCxnSpPr>
            <p:spPr>
               <a:xfrm flipV="1">
                  <a:off x="2711179" y="2176333" />
                  <a:ext cx="990997" cy="505215" />
               </a:xfrm>
               <a:prstGeom prst="bentConnector3">
                  <a:avLst />
               </a:prstGeom>
               <a:ln>
                  <a:tailEnd type="arrow" />
               </a:ln>
            </p:spPr>
            <p:style>
               <a:lnRef idx="2">
                  <a:schemeClr val="accent1" />
               </a:lnRef>
               <a:fillRef idx="0">
                  <a:schemeClr val="accent1" />
               </a:fillRef>
               <a:effectRef idx="1">
                  <a:schemeClr val="accent1" />
               </a:effectRef>
               <a:fontRef idx="minor">
                  <a:schemeClr val="tx1" />
               </a:fontRef>
            </p:style>
         </p:cxnSp>

**Comment by adamshakhabov** [comment]
Yes, I think we can add an API to create a new shape from raw XML content. I will investigate this.

**Comment by samcov** [comment]
Fantastic, it could solve some immediate issues!!!

**Comment by adamshakhabov** [comment]
The new method `IShapeCollection.AddLine()` was added in version [**0.42.0**](https://github.com/ShapeCrawler/ShapeCrawler/releases/tag/v0.42.0). Here's an example of how to use it:

```c#
var pres = SCPresentation.Create();
var xml = File.ReadAllText("line-shape.xml");
var shapes = pres.Slides[0].Shapes;

var lineShape = shapes.AddLine(xml);

pres.SaveAs("some.pptx");
```

**line-shape.xml**
```xml
<p:cxnSp xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
  xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">
  <p:nvCxnSpPr>
    <p:cNvPr id="1" name="Line">
      <a:extLst>
        <a:ext uri="{FF2B5EF4-FFF2-40B4-BE49-F238E27FC236}">
          <a16:creationId xmlns:a16="http://schemas.microsoft.com/office/drawing/2014/main"
            id="{9DF8435C-6FDF-AEDE-B5FC-18D871347979}" />
        </a:ext>
      </a:extLst>
    </p:cNvPr>
    <p:cNvCxnSpPr />
    <p:nvPr />
  </p:nvCxnSpPr>
  <p:spPr>
    <a:xfrm>
      <a:off x="1536700" y="1568450" />
      <a:ext cx="1206500" cy="0" />
    </a:xfrm>
    <a:prstGeom prst="line">
      <a:avLst />
    </a:prstGeom>
  </p:spPr>
  <p:style>
    <a:lnRef idx="1">
      <a:schemeClr val="accent1" />
    </a:lnRef>
    <a:fillRef idx="0">
      <a:schemeClr val="accent1" />
    </a:fillRef>
    <a:effectRef idx="0">
      <a:schemeClr val="accent1" />
    </a:effectRef>
    <a:fontRef idx="minor">
      <a:schemeClr val="tx1" />
    </a:fontRef>
  </p:style>
</p:cxnSp>
```
