### ISSUE TITLE
Alignment is displayed correctly only in the online editor

### ISSUE THREAD

**Issue by natsurkan** [ShapeCrawler/ShapeCrawler#476]
var shapeCollection = pres.Slides[1].Shapes;

            var table = (ITable)shapeCollection.First(sp => sp is ITable);

            var textFrame = table.Rows[2].Cells[2].TextFrame;

            textFrame.Text = "75";

            var paragraph = textFrame.Paragraphs.First();

            var font = paragraph.Portions.First().Font;

            paragraph.Alignment = SCTextAlignment.Center;

            font.Size = 22;

            font.ColorFormat.SetColorByHex("#00FF00");

            pres.Save();

PowerPoint
![Capture](https://user-images.githubusercontent.com/36164314/225324827-e0cb6220-528f-413b-97d6-92b2664d28f0.PNG)
Online Editor
![OnlineEditor](https://user-images.githubusercontent.com/36164314/225324839-23106062-81bf-48d2-a3ac-dd0279d673fb.PNG)

**Comment by adamshakhabov** [comment]
@natsurkan, thank you for the Bug Report. I was able to reproduce this issue. Will fix it.

**Comment by adamshakhabov** [comment]
Fixed. Please check it with this beta version [**v0.42.1-beta.2**](https://github.com/ShapeCrawler/ShapeCrawler/files/10984599/ShapeCrawler.0.42.1-beta.2.nupkg.zip)
