### ISSUE TITLE
Remove Chart Series

### ISSUE THREAD

**Issue by adamshakhabov** [ShapeCrawler/ShapeCrawler#491]
### Discussed in https://github.com/ShapeCrawler/ShapeCrawler/discussions/489

<div type='discussions-op-text'>

<sup>Originally posted by **Myles-JB** April 10, 2023</sup>
Hi,
I was wondering if it would be possible to dynamically update charts using shape crawler but not sure if it's possible.

I have a template pptx file with a dummy data chart that I want to update and insert data that I generate at run time.

The number of series/bars are dynamic based on data I'm generating which is where my problem lies. I can update already existing chart series but unable to add new series/ remove already existing.
</div>

**Comment by freshe** [comment]
Fantastic project! Upvote for this feature : )
