### ISSUE TITLE
Hyperlink to file throws exception

### ISSUE THREAD

**Issue by nicolajteknikteamet** [ShapeCrawler/ShapeCrawler#518]
When setting a hyperlink to filename an exception is thrown "Hyperlink is invalid.". 
Powerpoint should be able to link to other presentations.

Code below throws the exception.

using var sourcePresentation = SCPresentation.Open("SourceTemplate.pptx");
if (File.Exists("NewPresentation.pptx"))
{
    File.Delete("NewPresentation.pptx");
}

sourcePresentation.SaveAs("NewPresentation.pptx");

//create four shapes with a long text in each
var slide = sourcePresentation.Slides[0];
for (int i = 0; i < 4; i++)
{
    var shape = slide.Shapes.AddRectangle(150, 100 + 100 * i, 500, 50);
    shape.TextFrame.Text = "This is a long text #" + i;
    
    shape.TextFrame.Paragraphs[0].Portions[0].Hyperlink = "SourceTemplate.pptx";
}

sourcePresentation.Save();

**Comment by adamshakhabov** [comment]
Thank you for the bug report. Please check this fix [**v0.45.3-beta.1**](https://github.com/ShapeCrawler/ShapeCrawler/files/11781454/ShapeCrawler.0.45.3-beta.1.nupkg.zip)
