### ISSUE TITLE
Chage the table height or change Row height

### ISSUE THREAD

**Issue by Akshay-Warule** [ShapeCrawler/ShapeCrawler#532]
When we give height to table or height given to row nothing change happen in  pptx .
how to increase height of the row or height of the table . we are able to change Columns Width and Table width it working fine. But table height or row height not changed according to value given

  using IPresentation source = SCPresentation.Create();
     var slideMaster1 = source.Slides[0];
var table = slideMaster1.Shapes.AddTable(x: 60, y: 500, columnsCount: 2, rowsCount: 10);
        table.Width = 900;
        table.Height = 900; //not working
		
		table.Columns[0].Width = 600;
        table.Columns[1].Width = 600;
        var row = table.Rows.Add();
      //  row.Height = 100;//not working
        var cell = row.Cells[0];

        cell.TextFrame.Text = "Akshay";

**Comment by Akshay-Warule** [comment]
var tableAutoShape = table as ITable;

        tableAutoShape.Height = 1300;// not working

I also tried this to change table Height but it is not working. How can I change Table height and Row height . Also I want to hide table Vertical Line which are on its outline and increase thickness of horizontal line in table. Please Tell me that how can I do that.

**Comment by Akshay-Warule** [comment]
when the bug solve Comment here

**Comment by adamshakhabov** [comment]
@Akshay-Warule, please check this beta version: [**v0.46.0-beta.3**](https://github.com/ShapeCrawler/ShapeCrawler/files/11952353/ShapeCrawler.0.46.0-beta.3.nupkg.zip)

**Comment by Akshay-Warule** [comment]
Thanks, we are able to change row height. but can you tell us how to change table or row color. and can we increase width of horizontal lines of table and give them color.

var table = slideMaster1.Shapes.AddTable(x: 60, y: 500, columnsCount: 2, rowsCount:5);
        var tableAutoShape = table as ITable;

         tableAutoShape.Outline.Color = "ff0000";// not allowed becz Color allow only in IAutoshape not in ITable

//another Way

 var autoshapeOfTable = (ITable)slideMaster1.Shapes.Where(sp => sp.Name == table.Name).FirstOrDefault();
// autoshapeOfTable  doesn not give any method to set color.

**Comment by adamshakhabov** [comment]
- Set Font Size of Table Cell - `table.Rows[0].Cells[0].TextFrame.Paragraphs[0].Portions[0].Font.Size = 30`
- Set Color of Table Cell Fill - `table.Rows[0].Cells[0].Fill.SetColor("00ff00")`
- Set Color of Text of Table Cell - `table.Rows[0].Cells[0].TextFrame.Paragraphs[0].Portions[0].Font.ColorFormat.SetColorByHex("Ff0000")`
- Set Width of Horizontal Line of Table Row - Not available yet https://github.com/ShapeCrawler/ShapeCrawler/issues/546
- Set Color of Horizontal Line of Table Row - Not available yet https://github.com/ShapeCrawler/ShapeCrawler/issues/547
