### ISSUE TITLE
Unable to cast object of type 'ShapeCrawler.SCAutoShape' to type 'ShapeCrawler.ITable'

### ISSUE THREAD

**Issue by huchim** [ShapeCrawler/ShapeCrawler#536]
There's an error when trying to add a table to an slide.

Shape collection is returning a `SCTable` (`sourceTable`) but method `Add` is returning a `SCAutoShape`.

```cs
// SCTable
var sourceTable = ComponentsSlide.Shapes.First(c => c.Name == _options.TableName);
// SCAutoShape
var targetTable = (ITable)record.Slide.Shapes.Add(sourceTable);
// Unable to cast object of type 'ShapeCrawler.SCAutoShape' to type 'ShapeCrawler.ITable'
```

These classes inherits from `SCShape`:

- `SCChart` and `SCOLEObject` are not supported in the [529](https://github.com/ShapeCrawler/ShapeCrawler/pull/535)
- `SCGroupShape`: I don't how to return a new class of this type.
- `SCPicture`, `SCImage`, `SCTable`: I can create a factory for this types.
- `SCAutoShape`: This is the default.

I will work on a new PR 😄

**Comment by adamshakhabov** [comment]
You can skip the ability to add `IGroupShape`. We will do it in a separated ticket https://github.com/ShapeCrawler/ShapeCrawler/issues/539

Thanks a lot!

**Comment by huchim** [comment]
Hi!

`AutoShapeCreator` is able to  create an instance of `SCShapeGroup` 

```cs
rivate IShape? GetShape(AutoShapeCreator autoShapeCreator, TypedOpenXmlCompositeElement pShapeTreeChild)
{
    if (pShapeTreeChild is P.GroupShape pGroupShape)
    {
        return new SCGroupShape(pGroupShape, this.ParentSlideStructure, this);
    }
    shape = autoShapeCreator.FromTreeChild(pShapeTreeChild, this.ParentSlideStructure, this);
    // ...
    return shape;
}
```

"Auto creator" works fine... 

```cs
// Clone shape tree child.
var typedCompositeElement = (TypedOpenXmlCompositeElement)scShape.PShapeTreeChild.CloneNode(true);

var newShape = this.GetShape(this.autoShapeCreator, typedCompositeElement);
```

```cs
SCTable a = slide.Shapes.First(c => c.Name == "table");
var res = slide.Shapes.Add(a);

// ** res is SCTable
```

The problem is with SCChart and SCOLEObject, SCPicture, SCImage (audio, video)... take a look at GH-537

**Comment by adamshakhabov** [comment]
Ok. Then you can skip Chart, OLE Object, Picture, Audio and Video. We will do it later.
