### ISSUE TITLE
Change the size of cell's border

### ISSUE THREAD

**Issue by ashahabov** [ShapeCrawler/ShapeCrawler#546]
Add the capability to change the size of a table cell's border.

![image](https://github.com/ShapeCrawler/ShapeCrawler/assets/5969304/bf60fc1b-4636-4354-b832-b68ace0acc78)

- [x] Top Border
- [x] Bottom Border
- [x] Left Border
- [x] Right Border

**Comment by Akshay-Warule** [comment]
Comment here after completion, and give example how to use it

**Comment by Akshay-Warule** [comment]
can you tell when these functionality available for us

**Comment by adamshakhabov** [comment]
I will try to implement this by 21.07.

**Comment by FrenkieWang** [comment]
Hello, I found it is feasible to 
**Update Row's Height** or **Update Column's Width** using C# **ShapeCrawler**.

Please try my code, it will generate a PowerPoint - _Text 1_ on your desktop,
which has a Table on its first Slide.

The second Column's Width and third Row's Height has been changed.
Please check.

```
using System;
using System.IO;
using ShapeCrawler;

class Program
{
    static void Main(string[] args)
    {
        // create a new presentation
        var pres = new Presentation();

        ISlide slide = pres.Slides[0];
        slide.Shapes.AddTable(40, 40, 6, 5);

        var table = (ITable)slide.Shapes.Last();

        // Update 2nd Column's Width 
        table.Columns[1].Width = 400;
        // Update 3rd Row's Height 
        table.Rows[2].Height = 300;

        // Get the Path of Desktop
        string desktopPath = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);

        // Assgin the complete Path to save PPT File
        string pptFilePath = Path.Combine(desktopPath, "Text1.pptx");
        pres.SaveAs(pptFilePath);

        Console.WriteLine($"PPT has been saved to：{pptFilePath}");
    }
}
```
![Update Table Row Height and Column Width](https://github.com/ShapeCrawler/ShapeCrawler/assets/72019959/729aa3c4-b797-41ef-8b54-809424702d8f)

**Comment by ashahabov** [comment]
@FrenkieWang, you are right. However, the title of the issue was a bit wrong. It was about border's width.

I have made the appropriate changes to the description.
