### ISSUE TITLE
Cannot set Fill of newly added Rectangle.

### ISSUE THREAD

**Issue by mcxbe** [ShapeCrawler/ShapeCrawler#558]
```
namespace TesterApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // opens presentation from the file path
            var presentation = SCPresentation.Create();
            var slide = presentation.Slides[0];

            var shape = slide.Shapes.AddRectangle(0, 0, 100, 100);
            shape.Fill.SetColor("0000FF");

            presentation.SaveAs("test.pptx");
        }
    }
}
```

When running the code above, I would expect a rectangle with a blue solid fill, however the rectangle has no fill. Similarly, the wiki Solid Fill example does not work for me unless the shape already had a fill colour.

I am running ShapeCrawler 0.46.

Thanks for your great work so far.

![image](https://github.com/ShapeCrawler/ShapeCrawler/assets/1762486/e782b068-6f9b-436f-b9e1-662073a7a910)

**Comment by mcxbe** [comment]
It looks like the order of the properties matters. If I manually set the fill and save the PowerPoint, the fill comes before the outline inside the ShapeProperties. Then if I extract the PowerPoint created with ShapeCrawler and manually flip the Outline and Fill tags and re-zip the PowerPoint it works as expected.

**Comment by adamshakhabov** [comment]
@mcxbe, thank you for the bug report and your research. I was able to reproduce this issue.

**Comment by adamshakhabov** [comment]
@mcxbe, the issue was fixed. Please check this beta version [**v0.47.1-beta.1**](https://github.com/ShapeCrawler/ShapeCrawler/files/12294414/ShapeCrawler.0.47.1-beta.1.zip)
