### ISSUE TITLE
Vertically Merging on Tables Causes Incorrect Cell References

### ISSUE THREAD

**Issue by mcxbe** [ShapeCrawler/ShapeCrawler#564]
When attempting to vertically merge cells in a table, certain merges cause the ATableCell backing field to point to the wrong cell.

To reproduce:

```
class Program
{
    static void Main(string[] args)
    {
        var presentation = SCPresentation.Create();
        var slide = presentation.Slides[0];

        var table = slide.Shapes.AddTable(0, 0, 4, 2);
        table.MergeCells(table[1, 3], table[0,3]);
        table[1, 1].Fill.SetColor("00FF00");

        presentation.SaveAs("test.pptx");
    }
}
```

In this code I create a 2 row by 4 column table. I then merge the right-most cells into a single column. Then I attempt to set the fill of cell[1,1] to green, however cell [0,1] changes instead. Also note that `table[1,1] == table[0,1]` becomes true.

**Comment by adamshakhabov** [comment]
@mcxbe, check this fix [**v0.47.1-beta.2**](https://github.com/ShapeCrawler/ShapeCrawler/files/12305832/ShapeCrawler.0.47.1-beta.2.nupkg.zip)

**Comment by mcxbe** [comment]
Looks like the above issue is fixed however there still some issues with table merging unfortunately. Take this case for example:

```
class Program
{
    static void Main(string[] args)
    {
        // opens presentation from the file path
        var presentation = SCPresentation.Create();
        var slide = presentation.Slides[0];

        var table = slide.Shapes.AddTable(0, 0, 4, 2);
        table.MergeCells(table[0, 0], table[0, 1]);
        table.MergeCells(table[1, 1], table[1, 2]);

        presentation.SaveAs("test.pptx");
    }
}
```

The result should be a 2 row x 3 column table, with cells 0 and 1 being merged on the first row, and cells 1 and 2 being merged on the second row, however the first row of the table ends up with only two cells (cells 0, 1 and 2 merged).

Sorry for these weird cases!

**Comment by adamshakhabov** [comment]
@mcxbe, you do a good job with the _quality_ bug report👍 Thank you. 

I will take a look later.

**Comment by adamshakhabov** [comment]
@mcxbe, check this [**v0.47.1-beta.3**](https://github.com/ShapeCrawler/ShapeCrawler/files/12330308/ShapeCrawler.0.47.1-beta.3.nupkg.zip)

**Comment by mcxbe** [comment]
I have another one for you sorry!

```
class Program
{
    static void Main(string[] args)
    {
        var presentation = SCPresentation.Create();
        var slide = presentation.Slides[0];

        var table = slide.Shapes.AddTable(0, 0, 4, 2);
        table.MergeCells(table[0, 1], table[1, 1]);

        presentation.SaveAs("test.pptx");
    }
}
```

This one should simply merge the 2nd column vertically, however the 3rd column also gets merged. This behaviour is the same for any column your try to merge, other than the first column.

**Comment by adamshakhabov** [comment]
@mcxbe, check this [**v0.47.1-beta.4**](https://github.com/ShapeCrawler/ShapeCrawler/files/12383185/ShapeCrawler.0.47.1-beta.4.nupkg.zip)

**Comment by mcxbe** [comment]
Hi @ashahabov. Sorry for the late response, I've been away. Had a reasonable play with version 0.48 and can't see any remaining issues. Thanks for your help, I will close this issue.
