### ISSUE TITLE
Allow setting background on slides produced by AddEmptySlide

### ISSUE THREAD

**Issue by siegfriedpammer** [ShapeCrawler/ShapeCrawler#577]
```cs
var slide = presentation.Slides.AddEmptySlide(SCSlideLayoutType.Blank);
slide.Background.SetImage(background); // always crashes because slide.Background is null and there is no public API to set it.
```

I am very new to this library and would like to learn how to use it to create new presentations from scratch (i.e. without loading a template pptx) thanks!

**Comment by ashahabov** [comment]
@siegfriedpammer, it was bug. Please check fix: [**v0.48.1-beta.1**](https://github.com/ShapeCrawler/ShapeCrawler/files/12386439/ShapeCrawler.0.48.1-beta.1.nupkg.zip)
