### ISSUE TITLE
is it possible to add more features concerning Audio file insertion?

### ISSUE THREAD

**Issue by qchen-fdii-cardc** [ShapeCrawler/ShapeCrawler#579]
Recently I tried to produce mp4 file from a pptx.

I have successfully extracted notes for each slide, produced mp3 files, and inserted to slides correspondedly.

The process was every smooth, and the API are clear and straight-forward.  Thank you all!

If someone could add several features, it will be even better.

1. Add wav files proves to be difficult, the MIME property is read-only;
2. Change the play mode of the audio to autoplay could be very helpful.

Or I hope someone can give me directions for some other packages(open-source) which can do these.

Thanks all and have a nice day.

**Comment by qchen-fdii-cardc** [comment]
> @qchen-fdii-cardc, thank you for your feedback!
>
> 1. Could you please clarify. Are you talking about adding a _new_ audio shape to the slide with wav-file's content?
> 2. I've created a separate issue [Automatically playback audio #581](https://github.com/ShapeCrawler/ShapeCrawler/issues/581) for this feature. We will schedule it.

Happy to see that, thanks.

Automatically playback and/or hide when playing are what I can use.

And, there is another problem.

I have difficulty to add a wav file. When add a wav file, MIME of the shape was automatically set to mpeg, Which cause PowerPoint fail to play the raw sequence inserted. I had to transfer it to a mp3 file to get what I want.

My code looks as follows.

```FSharp
#r "nuget: ShapeCrawler, 0.48.0"


open System.IO
let insertAudio (slide:ShapeCrawler.ISlide) (fn:string) =
    use stream =  File.Open(fn, FileMode.Open)
    let audio = slide.Shapes.AddAudio(10, 10, stream)
    slide


let producePPTWithAudioFromNote (inputFile:string) (outputFile:string) =
    use p = ShapeCrawler.SCPresentation.Open(inputFile)

    p.Slides
    |> Seq.iter (fun o ->
        let notes = o.SDKSlidePart.NotesSlidePart.NotesSlide.InnerText
        let [n; num] =
            match removeLastNumber notes with
            | Some [note;number] -> [note; number]
            | _ -> [""; "0"]
        let fn = sprintf $"note-{num}.wav"
        do produceAudio n fn
        let mp3fn = wav2mp3 fn
        if mp3fn = fn then
            failwith $"Error produce mp3 file from {fn}"
        else
            insertAudio o mp3fn |> ignore
        )

    p.SaveAs(outputFile)
```

I had to use NAudio to implement a naive transfomer.

```FSharp
#r "nuget: NAudio, 2.2.1"

open NAudio.MediaFoundation
open NAudio.Wave
let wav2mp3 (source:string) =
    if source.EndsWith ".wav" then
        do MediaFoundationApi.Startup()
        use reader = new WaveFileReader(source)
        let outputFile = source.Replace(".wav", ".mp3")
        MediaFoundationEncoder.EncodeToMp3(reader, outputFile)
        do MediaFoundationApi.Shutdown()
        outputFile
    else
        source
```


Thanks.




________________________________
发件人: Adam Shakhabov ***@***.***>
发送时间: 2023年9月7日 15:46
收件人: ShapeCrawler/ShapeCrawler ***@***.***>
抄送: Q. Chen ***@***.***>; Mention ***@***.***>
主题: Re: [ShapeCrawler/ShapeCrawler] is it possible to add more features concerning Audio file insertion? (Issue #579)


@qchen-fdii-cardc<https://github.com/qchen-fdii-cardc>, thank you for your feedback!

  1.  Could you please clarify. Are you talking about adding a new audio shape to the slide with wav-file's content?
  2.  I've created a separate issue #581<https://github.com/ShapeCrawler/ShapeCrawler/issues/581> for this feature. We will schedule it.

―

**Comment by ashahabov** [comment]
@qchen-fdii-cardc, please check this [**v0.49.0-beta-1**](https://github.com/ShapeCrawler/ShapeCrawler/files/12562415/ShapeCrawler.0.49.0-beta.1.nupkg.zip)

A new `SCAudioType` was added. You can use it in the following way:

```c#
Stream wav = //...
var pres = SCPresentation.Open("my.pptx");
var shapes = pres.Slides[0].Shapes;

shapes.AddAudio(300, 100, wav, SCAudioType.WAVE);
```

**Comment by qchen-fdii-cardc** [comment]
Thanks very much. This is really helpful.


发件人: Adam ***@***.***>
发送时间: 2023年9月9日 1:43
收件人: ***@***.***>
抄送: Q. ***@***.***>; ***@***.***>
主题: Re: [ShapeCrawler/ShapeCrawler] is it possible to add more features concerning Audio file insertion? (Issue #579)


@qchen-fdii-cardc<https://github.com/qchen-fdii-cardc>, please check this v0.49.0-beta-1<https://github.com/ShapeCrawler/ShapeCrawler/files/12562415/ShapeCrawler.0.49.0-beta.1.nupkg.zip>

A new SCAudioType was added. You can use it in the following way:

Stream wav = //...

var pres = SCPresentation.Open("my.pptx");

var shapes = pres.Slides[0].Shapes;



shapes.AddAudio(300, 100, wav, SCAudioType.WAVE);

―
