### ISSUE TITLE
Net Framework 4.7.2 not supported in new versions			

### ISSUE THREAD

**Issue by natsurkan** [ShapeCrawler/ShapeCrawler#607]
I use NET framework 4.7.2 and wanted to update the version from 0.41.2 to the latest but there is a problem with installing AngleSharp.css 
"Unable to find a version of 'AngleSharp' that is compatible with 'AngleSharp.Css 0.17.0 constraint: AngleSharp (>= 0.17.0 && < 0.18.0)'.". Is it possible to fix this so that I can continue working with Net Framework?

**Comment by ashahabov** [comment]
@natsurkan, thank you for the bug report👍

I'm working on fix.

**Comment by ashahabov** [comment]
@natsurkan, it has been fixed. Please check the latest version [**v0.50.1**](https://github.com/ShapeCrawler/ShapeCrawler/releases)

**Comment by natsurkan** [comment]
thanks it's fixed!!!
