### ISSUE TITLE
System.InvalidOperationException: 'Sequence contains no matching element'

### ISSUE THREAD

**Issue by UndefinedScope** [ShapeCrawler/ShapeCrawler#615]
While using this example (https://github.com/ShapeCrawler/ShapeCrawler/wiki/Examples#picture) I'm getting the exception in row 30 in Shapes.cs: public T GetById<T>(int id) where T : IShape => (T)this.ShapesCore().First(shape => shape.Id == id);

The slide contains an image placeholder. 

Any advice? Thank you!

**Comment by UndefinedScope** [comment]
I'm using it this way
var picture = presentation.Slides[5].Shapes.GetByName<IPicture>(6);

If I change the code to this
var picture = presentation.Slides[5].Shapes.GetByName<IPicture>("Picture Placeholder 3");

The exception in the row 32
System.InvalidCastException: 'Unable to cast object of type 'ShapeCrawler.ShapeCollection.RootShape' to type 'ShapeCrawler.IPicture'.'

**Comment by ashahabov** [comment]
@UndefinedScope, I am unable to reproduce this exception issue. Could you please attach your presentation? 

If the presentation contains sensitive data and cannot be publicly shared, you can send it to theadamo86@gmail.com.
