### ISSUE TITLE
Error while saving, Framework 4.7.2

### ISSUE THREAD

**Issue by natsurkan** [ShapeCrawler/ShapeCrawler#621]
Use framework 4.7.2, when saving a presentation in a stream or path, we get an error. All this happens only when accessing the table without attempting to write or change. We copied the table from the tests into the presentation, everything works fine. Below I attach screenshots and a presentation with a problem table.
[template.pptx](https://github.com/ShapeCrawler/ShapeCrawler/files/13966280/template.pptx)
![photo_2024-01-17_19-00-48](https://github.com/ShapeCrawler/ShapeCrawler/assets/36164314/eee5bba4-afc3-44a3-a868-70e70b4e5439)
![Capture](https://github.com/ShapeCrawler/ShapeCrawler/assets/36164314/14168004-ce96-480e-8c10-17247cb036fa)

**Comment by ashahabov** [comment]
@natsurkan, thank you for the bug report. I was able to reproduce it. Will work on fix.

**Comment by BiDuang** [comment]
Fixed at latest Release version, please take a look.
