### ISSUE TITLE
[Bug] - Not recognizing table template when editing pptx at `.AsTable()`

### ISSUE THREAD

**Issue by wh1t3h47** [ShapeCrawler/ShapeCrawler#631]
Hello,
Firstly, I'd like to thank you for your project, it's very easy to use and good library.
However I ran into a few issues:
Since the behavior of the library is hard to customize and undocumented (think about changing font color, changing table styles, border, etc), I used an already existing powerpoint and opened it. This document has a few premade components referenced by an enum, as you can see by the logs, the library detects the component as a Table indeed, however, it fails some internal checking 

Steps to reproduce:
Create a PPT, create a first slide and put a table inside it.
In the initialization process, open the already present pptx and add a new slide (it's not necessary,  but it's the case scenario where I'm running it).

```csharp
            var templateSlide = ppt.Slides[0];
            var templateShape = templateSlide.Shapes.GetById<ITable>((int)_ShapeName.GenericTable);
            Console.WriteLine("got shape");
```
- `_ShapeName.GenericTable` is the ID of the table already present in the PPT

### this one clones the table and make sure it's still a table
```csharp
            ppt.Slides[ppt.Slides.Count - 1].Shapes.Add(templateShape);
            var tableShape = shapes[shapes.Count - 1];
            Console.WriteLine($"got tableShape {tableShape.ShapeType} {tableShape.Id}");
            if (tableShape.ShapeType != ShapeType.Table)
            {
                return;
            }
```

### this one throws the error
```csharp
            tableShape.Width = (int)width;
            tableShape.Height = (int)height;
            tableShape.X = (int)x;
            tableShape.Y = (int)y;

            for (int row = 0; row < rowCount; row++)
            {
                for (int col = 0; col < colCount; col++)
                {
                    Console.WriteLine("Before error");
                    var cell = tableShape.AsTable().Rows[row].Cells[col];
                    Console.WriteLine("Will not run");
                    // ...

```

Logs:
```
got shape
got tableShape Table 7
Before error
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      ShapeCrawler.Exceptions.SCException: The shape is not a table. Use ShapeType property to check if the shape is a table.
      at ShapeCrawler.ShapeCollection.Shape.AsTable()
```

As you can see, ShapeType is indeed "Table"

**Comment by ashahabov** [comment]
Hello @wh1t3h47. Thank you for your feedback🙂

I was able to reproduce this bug. Will fix.

**Comment by ashahabov** [comment]
Fixed. Please check the latest version.
