### ISSUE TITLE
Using ShapeCrawler in .Net Framework project (a VSTO addin)

### ISSUE THREAD

**Issue by sergedc** [ShapeCrawler/ShapeCrawler#635]
Hi all, 

I am trying to use ShapeCrawler in a VSTO addin (.net framework!). From my current research it seems that it is not possible to integrate a .Net 8.0 library into a .Net Framework project. But on the other hand I saw someone on the forum ask a question about such a .Net Framework. 

Is it possible? and if so how? 

My experience has been that using ShapeCrawler (from nuget packages) is a .Net 8.0 project works but in a .Net Framework project does not work (errors related with "Memory stream is not expandable") 

I was advised by [BiDuang](https://github.com/BiDuang) to try a local clone with Fix 630 (https://github.com/ShapeCrawler/ShapeCrawler/pull/630) , but then I get the error: Project '..\ShapeCrawler\src\ShapeCrawler\ShapeCrawler.csproj' targets 'net8.0'. It cannot be referenced by a project that targets '.NETFramework,Version=v4.8'.

**Comment by ashahabov** [comment]
Hello.

The fix from @BiDuang was applied, and the new version **[v0.50.2](https://github.com/ShapeCrawler/ShapeCrawler/releases/tag/v0.50.2)** of the library was released a few minutes ago🙂 Please check it out.

**Comment by sergedc** [comment]
It works! So it is possible to use a .Net 8.0 library in a .Net Framework project!

**Comment by BiDuang** [comment]
> It works! So it is possible to use a .Net 8.0 library in a .Net Framework project!

I'm afraid it can't. Some syntax may not compatible.

**Comment by BiDuang** [comment]
> Hi all,
> 
> I am trying to use ShapeCrawler in a VSTO addin (.net framework!). From my current research it seems that it is not possible to integrate a .Net 8.0 library into a .Net Framework project. But on the other hand I saw someone on the forum ask a question about such a .Net Framework.
> 
> Is it possible? and if so how?
> 
> My experience has been that using ShapeCrawler (from nuget packages) is a .Net 8.0 project works but in a .Net Framework project does not work (errors related with "Memory stream is not expandable")
> 
> I was advised by [BiDuang](https://github.com/BiDuang) to try a local clone with Fix 630 (#630) , but then I get the error: Project '..\ShapeCrawler\src\ShapeCrawler\ShapeCrawler.csproj' targets 'net8.0'. It cannot be referenced by a project that targets '.NETFramework,Version=v4.8'.

Well, ShapeCrawler has multiple target platform... So you may need to select target framework in project configs.
