### ISSUE TITLE
Integrate ShapeCrawler with OpenXML SDK

### ISSUE THREAD

**Issue by sergedc** [ShapeCrawler/ShapeCrawler#637]
Hi, 

I was wondering if there is a way to Integrate OpenXML SDK code into a ShapeCrawler object, e.g. for an operation that ShapeCrawler cannot do yet? 

My use case is that I am creating a ppt (with many slides) using ShapeCrawler. But on some slides, I need to copy a chart from XL to PPT (and I do that by copying the OpenXML content). 

Currently I am doing the code below, but it is very slow because it needs to save the PPT before starting the OpenXML part and reopen it after. Also, i am having difficulties getting ShapeCrawler and the OpenXML SDK to talk to the same slide. Is there a better way to do this? Is there a way to insert OpenXML code directly into a ShapeCrawler  ISlide?

```
pres = new SC.Presentation(outputPath);
pres.Slides.Add(copyingSlide);
pres.Save();

//OpenXML XL code to find the chart
var bkPart = document.WorkbookPart;
Sheet sheet = bkPart.Workbook.Descendants<Sheet>().FirstOrDefault(s => s.Name == sheetName);
WorksheetPart wsPart = (WorksheetPart)bkPart.GetPartById(sheet.Id);
ChartPart cp = wsPart.DrawingsPart.ChartParts.FirstOrDefault();

//OpenXML PPT code to insert the chart
var presentationPart = presentationDocument.PresentationPart;
var slideIdList = presentationPart.Presentation.SlideIdList;
var lastSlideId = slideIdList.ChildElements.Cast<SlideId>().LastOrDefault();
SlidePart slidePart = (SlidePart)presentationPart.GetPartById(lastSlideId.RelationshipId);
ChartPart chartPart = slidePart.AddNewPart<ChartPart>();
chartPart.ChartSpace = (C.ChartSpace)cp.ChartSpace.Clone();
GraphicFrame graphicFrame1 = new GraphicFrame();
NonVisualGraphicFrameProperties nonVisualGraphicFrameProperties1 = new NonVisualGraphicFrameProperties(....);
graphicFrame1.Append(nonVisualGraphicFrameProperties1);
Transform transform1 = new Transform(new D.Offset { X = 442913L, Y = 2042933L }, new D.Extents { Cx = 5080809L, Cy = 2658533L });
graphicFrame1.Append(transform1);
D.Graphic graphic1 = new D.Graphic(....);
graphicFrame1.Append(graphic1);
slidePart.Slide.CommonSlideData.ShapeTree.AppendChild(graphicFrame1);
slidePart.Slide.Save(); 


// Back to ShapeCrawler
pres = new SC.Presentation(outputPath);
pres.Slides.Add(anotherSlide);
```

**Comment by ashahabov** [comment]
Hello,

if I understand correctly, the idea is to expose the underlying object of the Open XML SDK for _updating_. For example, by adding a new property `IChart.SDKChartPart` that holds the `DocumentFormat.OpenXml.Packaging.ChartPart` instance.

We've already practiced this, and we still have such properties in parts of the library, which should be removed.

The downside is that this completely breaks _encapsulation_, contradicting one of the main principles of the library, that states that all manipulations with the presentation should only be done via ShapeCrawler's objects. If an API is missing, we need to implement it🙂

**Comment by sergedc** [comment]
Hi, 

I understand, but at the moment there are quite a few things that SchapeCrawler is not doing yet. 

FYI, the above (closing, saving, reopening) was a catastrophe. 
I found out that non public members can be accessed this way, so this problem is resolved.
```
var sdkSlidePartField = slide.GetType().GetField("sdkSlidePart", BindingFlags.NonPublic | BindingFlags.Instance);
var slidePart = (SlidePart)sdkSlidePartField?.GetValue(slide);
```

And now I can continue with OpenXML SDK without any problem and get back to ShapeCrawler after i am done.

**Comment by ashahabov** [comment]
Maybe you're right 🤔, and we should temporarily give access to the underlying SDK objects, at least until the first stable 1.0 version that includes enough features.

Please provide (if you need) a list of the additional SDK objects you need besides `Slide.SlidePart` for the your above workflow. I will consider making them accessible.
