### ISSUE TITLE
Change Font to double, not Int

### ISSUE THREAD

**Issue by sergedc** [ShapeCrawler/ShapeCrawler#653]
In Powerpoint it is possible to set the font size as 8.3 or 7.2 or 10.8

However, Ifont.Size (used for a table like this: table[i, j].TextFrame.Paragraphs.First().Portions.First().Font.Size) is defined as an integer.

Thanks,
Serge

**Comment by jcoliz** [comment]
@ashahabov Would you be OK just changing the public interface, ergo a breaking change? Or would you prefer a separate `double` getter/setter?

**Comment by ashahabov** [comment]
Yes, it is ok to change on `IFont.Size` to `double` type.
