### ISSUE TITLE
Cannot Add new Slide when there is no Slide in the Presentation.

### ISSUE THREAD

**Issue by FrenkieWang** [ShapeCrawler/ShapeCrawler#658]
Hello,  I found there is a Bug in ShapeCrawler.
I **cannot Add new Slide if there is no Slide in the PowerPoint.**
If there is no Slide in the Presentation Object, I cannot add new Slide any more.

For example, in the code below.

```
using System;
using System.IO;
using ShapeCrawler;

class Program
{
    static void Main(string[] args)
    {
        var pres = new Presentation();

        ISlide currentSlide = pres.Slides[0];

        pres.Slides.Remove(currentSlide);

        pres.Slides.AddEmptySlide(SlideLayoutType.Blank);    

        string desktopPath = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
        string pptFilePath = Path.Combine(desktopPath, "Text1.pptx");
        pres.SaveAs(pptFilePath);

        Console.WriteLine($"PPT has been saved to：{pptFilePath}");
    }
}
```

When I remove the currentSlide, **pres.Slides.Count** will be 0.

If I use **pres.Slides.AddEmptySlide(SlideLayoutType.Blank);**  ,  
it will throw an Exception -- _"Sequence contains no elements"_
The Exception is located at _System.Linq.Enumerable.First[TSource]_.
![Exception Detail](https://github.com/ShapeCrawler/ShapeCrawler/assets/72019959/7d373a20-0d65-4396-8003-de07925af731)

Therefore, I am sure that the Original Code of ShapeCrawler has some flaw.
It did not handle the situation that the current Presentation has no Slide(slide count = 0).

**Comment by ashahabov** [comment]
Hello,

thank you for the bug report.
