### ISSUE TITLE
Add API to change series value

### ISSUE THREAD

**Issue by adamshakhabov** [ShapeCrawler/ShapeCrawler#66]
Add ability to update series the following chart types:
- [x] Pie chart
- [x] Bar chart
- [x] Line chart

**Comment by Offbeatmammal** [comment]
+1 for this, adding a setter for the `SeriesCollection[n].PointValues[i]` would be very powerful

as part of the work, can the Category (and Series) names be exposed as get and set?

**Comment by adamshakhabov** [comment]
Category name updating is part of #67 issue, but Series title updating can be made as part of the current issue.

With regard to using [Open-Xml-PowerTools](Open-Xml-PowerTools), yes, it is an awesome library and contains much knowledge on how to manipulate pptx via Open XML SDK! Just one concern is not updated for a long time. There are many open PRs that are not merged. But I am using it for slide adding task :)
