### ISSUE TITLE
Cannot Change Font's isBold and LatinName in the Table Cell

### ISSUE THREAD

**Issue by FrenkieWang** [ShapeCrawler/ShapeCrawler#669]
Hello, I found there is a Bug in ShapeCrawler.
I cannot the attribute **isBold, LatinName and OffsetEffect** of the Text in a **Table Cell.**

For example, in the code below.
```
using System;
using System.IO;
using ShapeCrawler;

class Program
{
    static void Main(string[] args)
    {
        // Create a new PPT and gets its First Slide
        var pres = new Presentation();
        ISlide slide = pres.Slides[0];

        // Create a Table and get the Table
        slide.Shapes.AddTable(40, 40, 6, 5);
        var table = (ITable)slide.Shapes.Last();

        // Add text into a Table Cell
        var cell = table[1, 2];
        cell.TextFrame.Text = "Hello";

        // Edit the Text Font in the Table Cell
        var cellFont = cell.TextFrame.Paragraphs.First().Portions.First().Font;
        cellFont.Size = 40;
        cellFont.LatinName = "Prelo Slab Bold";

        // Get the Path of Desktop
        string desktopPath = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);

        // Assgin the complete Path to save PPT File
        string pptFilePath = Path.Combine(desktopPath, "Text1.pptx");
        pres.SaveAs(pptFilePath);

        Console.WriteLine($"PPT has been saved to：{pptFilePath}");
    }
}
```
I created a Table and get the Table Cell in Row 2, Column 3.
I added a Text `Hello` in that Table Cell.

I can only change the Font Size of `Hello`.
However, if I try to change the Font's LatinName, 
it will always throws an Exception in Line 24,
which states _`Sequence contains no Element`_
![Font Exception2](https://github.com/ShapeCrawler/ShapeCrawler/assets/72019959/28fda1fa-f51e-4793-b61e-669263adef49)

I used BreakPoint to debug, I found that Exception will occur in the three attributes of Font:
1. isBold
2. LatinName
3. OffsetEffect
![Font Exception](https://github.com/ShapeCrawler/ShapeCrawler/assets/72019959/3cc69bef-1d8e-432b-b8c3-e014c617f685)

The Exception is located at System.Linq.Enumerable.First[TSource].
![Font Exception3](https://github.com/ShapeCrawler/ShapeCrawler/assets/72019959/a5c76dc4-3799-49ab-9dbc-531a491c511a)

Therefore, I am sure that the Original Code of ShapeCrawler has some bugs
It cannot change the **isBold, LatinName and OffsetEffect** of the Text in a **Table Cell.**

**Comment by ashahabov** [comment]
@FrenkieWang, thank you for the bug report. I was able to reproduce the issue.

**Comment by ashahabov** [comment]
Minimum code for repro:

```C#
var pres = new Presentation();
var slide = pres.Slides[0];
slide.Shapes.AddTable(40, 40, 6, 5);
var table = (ITable)slide.Shapes.Last();
var cell = table[1, 2];
cell.TextFrame.Text = "Test";
var cellFont = cell.TextFrame.Paragraphs.First().Portions.First().Font;

cellFont.LatinName = "Arial";
```
