### ISSUE TITLE
SVG AddPicture: Large-dimension SVG files lead to error opening in PowerPoint

### ISSUE THREAD

**Issue by jcoliz** [ShapeCrawler/ShapeCrawler#683]
1. Prepare an SVG file with a width and height attribute of 25in or larger, e.g. "25in" or "2500"
2. Using ShapeCrawler, create a new presentation
3. Using `AddPicture()`, add this SVG to the presentation, and save it
4. Open resulting presentation in PowerPoint
5. Notice: "PowerPoint found a problem with content in {file}. PowerPoint can attempt to repair the presentation.
6. Press "Repair"
7. Notice: Added picture is not displayed

Expected: Picture should be displayed. If you drag/drop this image onto a slide while running PowerPoint, it will be shrunk so it fits on the slide. e.g. square image touches the top and bottom of the slide.

**Comment by jcoliz** [comment]
Note that this also applies to non-SVG files. Try to `AddPicture()` with a >2500-pixel width PNG, and the same thing will happen.

**Comment by ashahabov** [comment]
@jcoliz, I've checked the output of test [AddPicture_too_large_adds_svg_picture](https://github.com/ShapeCrawler/ShapeCrawler/blob/21e0b691b3ba3dd76eb121dbb8bea6d771792476/test/ShapeCrawler.Tests.Unit/ShapeCollectionTests.cs#L395): it doesn't look like a PowerPoint experience:

![image](https://github.com/ShapeCrawler/ShapeCrawler/assets/5969304/5a60a866-ec42-4d3c-86b2-4b4de8fb475b)

Could you please check this out?

**Comment by jcoliz** [comment]
Hey @ashahabov , that image on the right is not the image used in this test. This test uses test-vector-image-large.svg. The image on the right above is test-vector-image-wide.svg.

When I added test-vector-image-large.svg to powerpoint manually, I get similar results as ShapeCrawler.

Admittedly, the result isn't ideal. It shows a tiny red dot in the upper-left corner of a giant rectangle. But it IS what PowerPoint does with this image.

The problem is that the test image sets width/height attributes but NOT a viewbox. That's not really a best practice. Properly-formed SVG file would have a viewbox. ShapeCrawler COULD detect this case, and write a viewbox into the svg data, however I don't have a way to write the SVG back out without causing the text-whitespace problem previously discussed.

Also, I could change the test image to add a viewbox, so it would look better when added manually. Though that doesn't operationally change anything that I can tell.
