### ISSUE TITLE
Sub-pixel precision for shape position and size

### ISSUE THREAD

**Issue by jcoliz** [ShapeCrawler/ShapeCrawler#686]
I'm doing a lot of work that revolves around precisely centering groups of shapes on both axes. Integer precision is insufficient for this. You can really tell looking at the slides that the centering is off by one pixel here and there. 

This has been fixed perfectly by using sub-pixel positioning and sizing. Prototype here: https://github.com/jcoliz/ShapeCrawler/tree/topic/decimal-positioning . I did this using decimals, but afterward I'm not convinced decimal is any better than double in this application.

Would like to contribute this back. Question for @ashahabov , how would you prefer it done?
1. Change int to double universally for size and position
2. Add separate properties for backward compat (this is how I did it my prototype)
3. Something else?

**Comment by ashahabov** [comment]
Let's convert `IPosition.X` and other position and size properties into `decimal` type. In the future, if there are any complaints about performance, we will add some `IPosition.FloatX`.
