### ISSUE TITLE
Get/Set corner radius of rounded rectangles

### ISSUE THREAD

**Issue by jcoliz** [ShapeCrawler/ShapeCrawler#707]
Currently, ShapeCrawler can create rounded rectangles, but cannot modify their corner radius. 

Propose the following.

```c#
/// <summary>
///     Represents a rectangle with rounded corners
/// </summary>
public interface IRoundRectangle: IShape
{
    /// <summary>
    ///     Gets or sets radius of corner in pixels.
    /// </summary>
    decimal CornerRadius { get; set; }
}
```

I have no idea how to do this, but it is possible in Powerpoint to adjust the corner radius. Also, it is not possible to SPECIFY the corner radius by typing in a number in PowerPoint. Ergo, we want to generate our slides with rounded rectangles in ShapeCrawler so we can precisely specify them.

**Comment by ashahabov** [comment]
My quick research says the corner radius is managed with `a:avLst`:

![image](https://github.com/ShapeCrawler/ShapeCrawler/assets/5969304/c816ad8c-11fb-4dc8-8c01-bc26455513f4)
