### ISSUE TITLE
Replacing textframe text leaves traces of previous text

### ISSUE THREAD

**Issue by rubenanton90** [ShapeCrawler/ShapeCrawler#718]
_Check the repo at https://github.com/rubenanton90/ShapeCrawlerTextBug , the offending pptx is [samplepptx_es.pptx](https://github.com/rubenanton90/ShapeCrawlerTextBug/blob/master/ShapeCrawlerTextBug/samplepptx_es.pptx), you can change the code to point to samplepptx.pptx, that one works fine_

Going through all the text frames in a slide and reversing their text:
`  foreach (ITextFrame item in slide.TextFrames())
    {
        item.Text = ReverseText(item.Text);
    }`
    _(Any other text replacement also fails in a similar way, reversing text is just an example)_
    results in some text not being replaced properly. For example, in the first slide, from the input text "Fichero powerpoint de ejemplo" instead of displaying the text "olpmeje ed tnioprewop orehciF", it displays "olpmeje ed tnioprewop orehciFpowerpoint de ejemplo"

Also tried some workarounds, such as going through each paragraph in the text or even using paragraph.ReplaceText(paragraph.Text, reversedText) to no avail

**Comment by edwardmcleodjones** [comment]
Seems to be an issue with `IParagraph.cs`, in this section:

https://github.com/ShapeCrawler/ShapeCrawler/blob/master/src/ShapeCrawler/Texts/IParagraph.cs#L96-L101

```csharp
            // To set a paragraph text we use a single portion which is the first paragraph portion.
            var baseARun = this.AParagraph.GetFirstChild<A.Run>() !;
            foreach (var removingRun in this.AParagraph.OfType<A.Run>().Where(run => run != baseARun))
            {
                removingRun.Remove();
            }
```

It doesn't actually remove **all** the `A.Run` elements that it is meant to, only the first element.

Copying the runs with `.ToList()` then iterating over that seems to fix it - the runs to be removed are actually removed, then the text can be set correctly on the base run as expected:

```csharp
            // To set a paragraph text we use a single portion which is the first paragraph portion.
            var baseARun = this.AParagraph.GetFirstChild<A.Run>() !;
            var remainingRuns = this.AParagraph.OfType<A.Run>().Where(run => run != baseARun).ToList();
            foreach (var removingRun in remainingRuns)
            {
                removingRun.Remove();
            }
```

**Comment by ashahabov** [comment]
@edwardmcleodjones, thank you for your fix https://github.com/ShapeCrawler/ShapeCrawler/pull/719 👍

@rubenanton90, could you please check your case with the latest version.

**Comment by rubenanton90** [comment]
Hi! Sorry for the delay. Can confirm it works properly in 0.53.1
Thank you @edwardmcleodjones  and @ashahabov for your great work!
