### ISSUE TITLE
Unable to decode the image from the supplied stream

### ISSUE THREAD

**Issue by chris-askbrian** [ShapeCrawler/ShapeCrawler#762]
I have quite weird problem as its pretty much really basic 

Im on ubuntu using net8.0 writing a classlib using ShapeCrawler v0.54.2

```
using ShapeCrawler;
namespace PptxLibrary
{
    public class PptxHelper
    {
        public void AddImgToPptx(string pptxPath, string imgPath)
        {
            var presentation = new Presentation(pptxPath);
            var slide = presentation.Slides[0];
            var imgStream = new FileStream(imgPath, FileMode.Open);
            slide.Shapes.AddPicture(imgStream);
            presentation.Save();
        }
    }
}
```
When using this code with an normal image it works without a problem, adding the picture and its done. With any kind of svg like this one: 
![svg](https://github.com/user-attachments/assets/5113f12f-d06f-4a5d-9703-098462a787c8)

I get a `ShapeCrawler.Exceptions.SCException: Unable to decode the image from the supplied stream.` Error

Not sure what I do wrong here (but tbh I'm not a skilled c# developer so I might have missed something but since It works with png I am not sure anymore)

**Comment by ashahabov** [comment]
@chris-askbrian, I was unable to reproduce this error. Could you please attach this SVG file?

**Comment by chris-askbrian** [comment]
I already did [Here](https://[private-user-images.githubusercontent.com/69350076/367754673-5113f12f-d06f-4a5d-9703-098462a787c8.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNzA4MTYsIm5iZiI6MTcyNzA3MDUxNiwicGF0aCI6Ii82OTM1MDA3Ni8zNjc3NTQ2NzMtNTExM2YxMmYtZDA2Zi00YTVkLTk3MDMtMDk4NDYyYTc4N2M4LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDA1NDgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzNmI5NDA1ODdjMDcyMjUyZWUwNzYwY2E0MzdjYzk0MjY2NjgzYWM3OGRhM2NhZDQ4MTc3MmM4MjUwNDBhYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.n2eZ8SWHikzux3rusZcZ4-ZWwVTg41VO00HrdY-kLfI](https://private-user-images.githubusercontent.com/69350076/367754673-5113f12f-d06f-4a5d-9703-098462a787c8.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNzA4MTYsIm5iZiI6MTcyNzA3MDUxNiwicGF0aCI6Ii82OTM1MDA3Ni8zNjc3NTQ2NzMtNTExM2YxMmYtZDA2Zi00YTVkLTk3MDMtMDk4NDYyYTc4N2M4LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDA1NDgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzNmI5NDA1ODdjMDcyMjUyZWUwNzYwY2E0MzdjYzk0MjY2NjgzYWM3OGRhM2NhZDQ4MTc3MmM4MjUwNDBhYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.n2eZ8SWHikzux3rusZcZ4-ZWwVTg41VO00HrdY-kLfI))

**Comment by ashahabov** [comment]
The link "Here" doesn't work.

**Comment by chris-askbrian** [comment]
Hmm you are right... weird github... 
Here the link to the icon uploaded to our cdn : [https://cdn.askbrian.dev/tmp/svg.svg](https://cdn.askbrian.dev/tmp/svg.svg)

**Comment by ashahabov** [comment]
Today I was able to reproduce this. Yes, it doesn't work on Ubuntu but works on Windows.

I will investigate this next.

**Comment by ashahabov** [comment]
@chris-askbrian, the installing `libgdiplus` using the following command helped me. Please check this on your side.

```bash
sudo apt install -y libgdiplus
```
