### ISSUE TITLE
Solid color background fill

### ISSUE THREAD

**Issue by jcoliz** [ShapeCrawler/ShapeCrawler#797]
Is it possible to set a solid color background fill on a slide? If so, please educate! If not, this issue tracks the need for it.

**Comment by ashahabov** [comment]
No, currently only image background is supported.

**Comment by jcoliz** [comment]
Thiis is in a `p:cSld`:

```xml
<p:bg>
    <p:bgPr>
        <a:solidFill>
            <a:srgbClr val="E6BB90"/>
        </a:solidFill>
        <a:effectLst/>
    </p:bgPr>
</p:bg>
```

**Comment by ashahabov** [comment]
Regard API changes, I would suggest doing the following update:

**Now:**

```C#
pre.Slides[0].Background.Update(imageStream);
```

**New:**

```C#
pre.Slides[0].Fill.SetPicture(imageStream);
pre.Slides[0].Fill.SetColor("32a852");
```

**Comment by jcoliz** [comment]
Yup, I landed in the same place.
