### ISSUE TITLE
Crop picture to shape

### ISSUE THREAD

**Issue by jcoliz** [ShapeCrawler/ShapeCrawler#798]
Need to crop pictures to shapes. Specifically a top rounded rectangle

The following is found within a `p:pic` created by one of our designers:

```xml
<p:spPr>
    <a:xfrm>
        <a:off x="4185868" y="1372955"/>
        <a:ext cx="3815133" cy="387350"/>
    </a:xfrm>
    <a:prstGeom prst="round2SameRect">
        <a:avLst>
            <a:gd name="adj1" fmla="val 22122"/>
            <a:gd name="adj2" fmla="val 0"/>
        </a:avLst>
    </a:prstGeom>
</p:spPr>
```

**Comment by ashahabov** [comment]
A possible new API to crop picture:

```C#
var pres = new Presentation("pre.pptx");
IPicture picture = pres.Slide(1).Picture("Picture 1");

picture.Crop(left:0.1, right:0.1, top:0.2, bottom:0.2); // Left and Right Crop is 10%, Top and Bottom Crop is 20%
```

**Comment by jcoliz** [comment]
The `picture.Crop` API noted above would allow for setting the crop frame, which is good. However, it's not enough for this issue. We need to be able to specify the geometry and corner size for this crop also.

**Comment by ashahabov** [comment]
Hmm, I didn't know that PowerPoint has feature "Crop to Shape". I think that's what you're talking about:

![image](https://github.com/user-attachments/assets/40d8256b-324e-4f69-b265-eb3a13dcb173)

**Comment by jcoliz** [comment]
Yup, that's the one. User can still set the cropping frame, as well as apply preset geometry. And if you choose a rounded rectangle, you'll notice there is a corner size handle as well.

**Comment by jcoliz** [comment]
Updated: I now think the clipping frame comes from `a:srcRect` within the `p:blipFill`

```xml
<p:blipFill rotWithShape="1">
    <a:blip r:embed="rId3">
        <a:alphaModFix amt="20000"/>
    </a:blip>
    <a:srcRect l="59" t="-295" r="19636" b="81332"/>
    <a:stretch/>
</p:blipFill>
```

**Comment by jcoliz** [comment]
Side note: As discussed in #804, the range of the cropping frame should be changed from 0.0-1.0 to 0-100 instead.
