### ISSUE TITLE
Maintainer's name should not be listed as the author of every presentation created by ShapeCrawler

### ISSUE THREAD

**Issue by jcoliz** [ShapeCrawler/ShapeCrawler#812]
Repro steps:
1. Using ShapeCrawler, create and save a new presentation
2. Load the resulting presentation in PowerPoint
3. Pick the File menu, then Info

Result: 
Adam is listed as the author and last modified by contact

Expected:
Ideally, just blank. If this is a required field, I'd argue for a required parameter when creating a presentation. Even better would be API to set all the info properties

More information:
Looking into `src\ShapeCrawler\Resources\new-presentation.pptx\docProps\core.xml`, we can see....

```xml
    <dc:title>PowerPoint Presentation</dc:title>
    <dc:creator>Adam Shakhabov</dc:creator>
    <cp:lastModifiedBy>Adam Shakhabov</cp:lastModifiedBy>
    <cp:revision>1</cp:revision>
    <dcterms:created xsi:type="dcterms:W3CDTF">2023-07-09T20:28:40Z</dcterms:created>
    <dcterms:modified xsi:type="dcterms:W3CDTF">2023-07-09T20:28:46Z</dcterms:modified>
```

**Comment by jcoliz** [comment]
@ashahabov I think is done now, eh?

**Comment by ashahabov** [comment]
Right. Thanks for the reminder👍
